name: NameThatMob
main: main.java.net.bigbadcraft.namethatmob.MobPlugin
version: 3.0
soft-depend: [Vault]
commands:
  namemob:
    description: Main command
    permission: namethatmob.use
    permission-message: §cYou do not have <permission>